"""Independent exhaustive verification of risk/Bridge identities and perturbation bounds."""
import argparse
import itertools
from pathlib import Path
import time
import numpy as np
from .bridge import qubo, ising, solve
from .research_common import write_json, digest, utc, Budget


def execute(root):
    budget = Budget(root, {'cpu_seconds': 7200, 'analytic_calls': 0, 'shots': 0},
                    {'verification': {'cpu_seconds': 7200, 'analytic_calls': 0, 'shots': 0}})
    budget.admit('sixty_cases', 'verification', {'cpu_seconds': 7000, 'analytic_calls': 0, 'shots': 0})
    rng = np.random.default_rng(2026090801)
    records = []
    for case in range(60):
        n = 2 + case % 9
        k = 1 + (case // 9) % n
        loadings = rng.normal(0, .01, (n, min(3, n)))
        factor = np.diag(rng.uniform(.1, 2, loadings.shape[1]))
        specific = rng.uniform(1e-5, 1e-3, n)
        sigma = loadings @ factor @ loadings.T + np.diag(specific)
        mu = rng.normal(0, .01, n)
        previous = rng.dirichlet(np.ones(n)) * rng.uniform(0, 1)
        cost = [0, .0005, .001, .002, .005][case % 5]
        risk_lambda = [.1, 1, 10][case % 3]
        matrix, offset = qubo(mu, sigma, k, risk_lambda, cost, previous)
        fields, coupling, shift = ising(matrix, offset)
        delta_mu = rng.normal(0, 1e-3, n)
        perturb = rng.normal(0, 1e-4, (n, n)); perturb = (perturb + perturb.T) / 2
        errors, perturbations, costs = [], [], []
        for bits in itertools.product([0., 1.], repeat=n):
            x = np.array(bits); w = x / k; z = 1 - 2 * x
            direct = -sum(mu[i] * w[i] for i in range(n))
            direct += risk_lambda * sum(w[i] * sigma[i, j] * w[j] for i in range(n) for j in range(n))
            direct += cost * sum(abs(w[i] - previous[i]) for i in range(n))
            errors.extend([abs(direct - (x @ matrix @ x + offset)), abs(direct - (fields @ z + z @ coupling @ z + shift))])
            if x.sum() == k:
                costs.append(direct)
                perturbations.append(abs(-delta_mu @ w + risk_lambda * w @ perturb @ w))
        bound = np.linalg.norm(delta_mu, np.inf) + risk_lambda * np.linalg.norm(perturb, 2) / k
        x, solved = solve(mu, sigma, k, risk_lambda, cost, previous)
        record = {'case': case, 'assets': n, 'k': k, 'all_binary_states': 2**n,
            'min_eigenvalue': float(np.linalg.eigvalsh(sigma).min()), 'maximum_energy_identity_error': max(errors),
            'maximum_feasible_perturbation': max(perturbations), 'perturbation_bound': float(bound),
            'exact_optimum': min(costs), 'heuristic_gap': max(0., solved['objective'] - min(costs)),
            'objective_scaling': {'mean': 1/k, 'risk': 1/k**2}, 'cash_previous': float(1 - previous.sum())}
        if max(errors) > 1e-10 or max(perturbations) > bound + 1e-12 or x.sum() != k or record['min_eigenvalue'] <= 0:
            raise ValueError('MATHEMATICAL_CONTRACT_CASE:' + str(case))
        records.append(record)
    budget.finish('sixty_cases', {'analytic_calls': 0, 'shots': 0})
    result = {'experiment_id': 'E01', 'run_id': root.name, 'execution_mode': 'CLASSICAL_EXACT_ENUMERATION',
        'scientific_status': 'LOCAL_VERIFIED', 'archive_status': 'RESULT_GENERATED', 'release_status': 'NOT_RELEASED',
        'synthetic_case_count': len(records), 'total_binary_states': sum(r['all_binary_states'] for r in records),
        'maximum_identity_error': max(r['maximum_energy_identity_error'] for r in records),
        'all_perturbation_bounds_hold': True, 'cases': records, 'created_at': utc(),
        'implementation_sha256': {'run_e01': digest(__file__), 'bridge': digest(Path(__file__).with_name('bridge.py'))},
        'scope': 'Synthetic mathematical interface evidence; stock data time/coverage evidence is generated by the stock derivation.'}
    write_json(root / 'result.json', result)
    print({k: result[k] for k in ['experiment_id', 'scientific_status', 'synthetic_case_count', 'maximum_identity_error']})


if __name__ == '__main__':
    p = argparse.ArgumentParser(); p.add_argument('--output', type=Path, required=True)
    execute(p.parse_args().output)
